apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: traefik
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true" # Optional: Make this the default IngressClass
spec:
  controller: traefik.io/ingress-controller
